### PR TITLE
use escape char to differentiate formatting from literal backslash

### PR DESCRIPTION
**Pull request by mojavelinux**
- use escape character to differentiate formatting marks from literal backslash
- add tests for manpage backend
- consolidate manify method

### CODE REVIEW

**Comment by ds26gte** [comment]
Hmm. Your changes work on sample manpages I pulled it into my fork. However, when I create a new PR back to asciidoctor, it fails the AppVeyor and Travis CI checks. This happens both when I simply merge your change, and also when I merge both it and the upstream asciidoctor. It's quite possible I ruined something in my branch. 

If you have a working fork that succeeds at the checks, you should probably merge to master directly. Anything I may have initially had in my `manpage-backslash-is-verbatim-inside-listing` branch is completely superseded by what you wrote anyway.

**Comment by mojavelinux** [comment]
I'll have a look. I'm sure we can get to the bottom of it.

**Comment by mojavelinux** [comment]
I had broken the tests on Ruby 1.8 and 1.9 (I'll be so happy when we can finally get rid of those archaic beasts).

Merged as 31feac906f023ca413dc96040c3464815fa3bee1.

Thanks!

Moving forward, we can be more confident about changes to the manpage converter now that we actually have some tests for it :)

**Comment by ds26gte** [comment]
Excellent; thanks! Here's to a new golden age of man pages. :-)

**Comment by mojavelinux** [comment]
:trophy:

**Comment by mojavelinux** [comment]
Thanks for pushing it to a new level!

**Pull request merged**
